def convertMonth(n):
  if not(isinstance(n, int)): return "Please use an integer between 1 and 12"
  elif n == 1: return "January"
  elif n == 2: return "February"
  elif n == 3: return "March"
  elif n == 4: return "April"
  elif n == 5: return "May"
  elif n == 6: return "June"
  elif n == 7: return "July"
  elif n == 8: return "August"
  elif n == 9: return "September"
  elif n == 10: return "October"
  elif n == 11: return "November"
  elif n == 12: return "December"
  else: return "Please use an integer between 1 and 12"